# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Pepper's Pawprint"
description: Mein Weg zum Hundetrainer

email: pepperspawprint@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/blog-background.jpg"

name: 'Wiebke'
author: 'Wiebke'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.peppers-pawprint.com" # the base hostname & protocol for your site
baseurl: ""

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	instagram
    url:	https://www.instagram.com/peppers_pawprint/
    desc: Follow me on instagram
