# ------------------------------------- #
# ---- General Settings --------------- #
# ------------------------------------- #
baseURL = "https://www.peppers-pawprint.com/"
title = "Pepper's Pawprint"
description = "Blog"
publishDir = "docs"
theme = "customized"

enableRobotsTXT = true       # generate robots.txt
enableEmoji = true           # use emoji support
hasCJKLanguage = true        # detect CJK languages for word count etc.
preserveTaxonomyNames = true # do not make tag names lowercase
rssLimit = 20                # limit number of entries in RSS feeds
removePathAccents = true     # fix taxonomies in foreign languages

# Pagination
# number of entries per page for archives, tags and categories
# since we don't have list view, recommend a large value
paginate = 10
paginatePath = "page"

# service plugins
googleAnalytics = "UA-157451297-1"
# change the tag in cookies.html functions and custom.js function

# language support # en / de translations present in i18n
defaultContentLanguage = "en"           # Default language to use
defaultContentLanguageInSubdir = true

# Links format
[permalinks]
  posts = "/posts/:slug/"
  categories = "/posts/category/:slug/"      # required
  tags = "/posts/tag/:slug/"                 # required
  pages = "/:slug/"

[author]                     # required
  name = "Pepper's Pawprint - Wiebke Meyer"

[sitemap]                    # required
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"


# ------------------------------------- #
# ---- Privacy ------------------------ #
# ------------------------------------- #
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = true 
    privacyEnhanced = false

# ------------------------------------- #
# ---- Other Params ------------------- #
# ------------------------------------- #
[params]
  since = "2020"             # Site creation time
  rssFullContent = true      # set true to use full content instead of summary

  # site info (optional)
  keywords = ["blog", "dogblog","hundeblog"]
  description = "Pepper's Pawprint Blog"
  siteLogoImage = "images/logo.png"     # shown besides logoTitle
  showAuthorCard = false # Whether to show author information below the article

  faviconImage = "images/favicon.png"     # shown besides logoTitle

  showMenuLanguages = true
  autoLoadComments = false # auto load comment when scrolling down

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "02 Jan 06"

  google_verification = ""  # Google_Verification

  # social accounts
  instagram =	"https://www.instagram.com/peppers_pawprint/"
  mail =	"mailto:pepperspawprint@gmail.com"
  mail_title =	"pepperspawprint@gmail.com"

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  basicCSS = ['bootstrap.4.1.3.min.css', 'fontawesome.5.2.0.css', 'cookieconsent.min.css']
  customCSS = ['default.css', 'layout.css']      # if ['custom.css'], load '/static/css/custom.css' file
  basicJS = ['jquery-3.3.1.slim.min.js', 'popper.min.js', 'bootstrap.4.1.3.min.js']
  customJS = ['custom.js']              # if ['custom.js'], load '/static/js/custom.js' file

# ------------------------------------- #
# ---- Related Articles --------------- #
# ------------------------------------- #
[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 50

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = true

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 200

[[related.indices]]
  name = "keywords"
  weight = 150

[[related.indices]]
  name = "tags"
  weight = 100


# ------------------------------------- #
# ----------- Resources --------------- #
# ------------------------------------- #
[[resources]]
  name = "logo"
  src = "static/images/logo.jpg"

# ------------------------------------- #
# ----------- Languages --------------- #
# ------------------------------------- #
[languages.en]
  languageCode = "en"
  languageName = "English"
  contentDir = "content/en"
  cookie_consent_info_url = "/information/cookies/"
  copyright = "All rights reserved."
  weight = 1 

  [[languages.en.menu.main]]
    name = "Blog"
    weight = 1
    identifier = "home"
    url = "/en/"

#  [[languages.en.menu.main]]
#    name = "Blog"
#    weight = 2
#    identifier = "blog"
#    url = "/posts/"

  [[languages.en.menu.main]]
    name = "About us"
    weight = 3
    identifier = "about"
    url = "/about/"

  [[languages.en.menu.social]]
    name = "Mail"
    weight = 5
    pre = '<i class="far fa-envelope"></i>'
    identifier = "mail"
    url = "mailto:pepperspawprint@gmail.com"

  [[languages.en.menu.social]]
    name = "Instagram"
    weight = 10
    pre = '<i class="fab fa-instagram"></i>'
    identifier = "instagram"
    url = "https://www.instagram.com/peppers_pawprint/"

  [[languages.en.menu.links]]
    name = "Privacy"
    weight = 5
    identifier = "privacy"
    url = "/privacy/"

  [[languages.en.menu.links]]
    name = "Imprint"
    weight = 10
    identifier = "impressum"
    url = "/impressum/"


[languages.de]
  languageCode = "de"
  languageName = "Deutsch"
  contentDir = "content/de"
  cookie_consent_info_url = "de/information/cookies/"
  copyright = ""
  weight = 2

  [[languages.de.menu.main]]
    name = "Blog"
    weight = 1
    identifier = "home"
    url = "/de/"

#  [[languages.de.menu.main]]
#    name = "Blog"
#    weight = 2
#    identifier = "blog"
#    url = "/posts/"

  [[languages.de.menu.main]]
    name = "Über uns"
    weight = 3
    identifier = "about"
    url = "/about/"

  [[languages.de.menu.social]]
    name = "Mail"
    weight = 5
    pre = '<i class="far fa-envelope"></i>'
    identifier = "mail"
    url = "mailto:pepperspawprint@gmail.com"

  [[languages.de.menu.social]]
    name = "Instagram"
    weight = 10
    pre = '<i class="fab fa-instagram"></i>'
    identifier = "instagram"
    url = "https://www.instagram.com/peppers_pawprint/"

  [[languages.de.menu.links]]
    name = "Datenschutz"
    weight = 5
    identifier = "privacy"
    url = "/privacy/"

  [[languages.de.menu.links]]
    name = "Impressum"
    weight = 10
    identifier = "impressum"
    url = "/impressum/"