# ------------------------------------- #
# ---- General Settings --------------- #
# ------------------------------------- #
baseURL = "https://www.peppers-pawprint.com/"
title = "Pepper's Pawprint"
description = "Blog"
publishDir = "docs"
theme = "customized"

enableRobotsTXT = true       # generate robots.txt
enableEmoji = true           # use emoji support
hasCJKLanguage = true        # detect CJK languages for word count etc.
preserveTaxonomyNames = true # do not make tag names lowercase
rssLimit = 20                # limit number of entries in RSS feeds
removePathAccents = true     # fix taxonomies in foreign languages

# Pagination
# number of entries per page for archives, tags and categories
# since we don't have list view, recommend a large value
paginate = 9
paginatePath = "page"

# service plugins
googleAnalytics = "UA-157451297-1"
# change the tag in cookies.html functions and custom.js function

# language support
defaultContentLanguage = "en"           # Default language to use
defaultContentLanguageInSubdir = true

# Links format
[permalinks]
  blog = "/blog/:slug/"
  categories = "/blog/category/:slug/"      # required
  tags = "/blog/tag/:slug/"                 # required
  pages = "/:slug/"

[author]                     # required
  name = "Pepper's Pawprint - Wiebke Meyer"

[sitemap]                    # required
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# ------------------------------------- #
# ---- Privacy ------------------------ #
# ------------------------------------- #
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.facebook]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = true 
    privacyEnhanced = false

# ------------------------------------- #
# ---- Other Params ------------------- #
# ------------------------------------- #
[params]
  since = "2020"             # Site creation time
  rssFullContent = true      # set true to use full content instead of summary

  # site info (optional)
  keywords = ["blog", "dogblog","hundeblog"]
  description = "Pepper's Pawprint Blog"
  siteLogoImage = "images/logo.svg"     # shown besides logoTitle
  showAuthorCard = false # Whether to show author information below the article

  faviconImage = "images/favicon.ico"     # shown besides logoTitle

  showMenuLanguages = true
  autoLoadComments = false # auto load comment when scrolling down

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "02 Jan 06"

  google_verification = ""  # Google_Verification


# ------------------------------------- #
# ---- Responsive Images -------------- #
# ------------------------------------- #

  # Highest width is 2500px for landscape and 1500px for portrait.
  # This will give both orientations roughly the same resolution and size.
  # Every landscape image will also be scaled down to 1500px and 1000px,
  # and portrait photos to 1000px and 750px wide.
  landscapePhotoWidths = [2500, 1500, 1000]
  portraitPhotoWidths = [1500, 1000, 750]

  [imaging]
  quality = 70

  ############################# social site ########################
  [[params.social]]
  icon = "far fa-envelope"
  link = "mailto:pepperspawprint@gmail.com"

  [[params.social]]
  icon = "fab fa-instagram"
  link = "https://www.instagram.com/peppers_pawprint/"

  [[params.social]]
  icon = "fab fa-facebook-f"
  link = "https://www.facebook.com/pepperspawprint/"

  [[params.social]]
  icon = "fab fa-youtube"
  link = "https://www.youtube.com/channel/UC7fRn-QEGp807IVhresK8AA"

# ------------------------------------- #
# ---- Related Articles --------------- #
# ------------------------------------- #
[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 50

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = true

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 200

[[related.indices]]
  name = "tags"
  weight = 100


# ------------------------------------- #
# ----------- Resources --------------- #
# ------------------------------------- #
[[resources]]
  name = "logo"
  src = "static/images/logo.jpg"

# ------------------------------------- #
# ----------- Languages --------------- #
# ------------------------------------- #
[languages.en]
  languageCode = "en"
  languageName = "English"
  copyright = "All rights reserved."
  weight = 1 

  [[languages.en.menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/en/"

  [[languages.en.menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/blog/"

  [[languages.en.menu.main]]
    name = "About us"
    weight = 3
    identifier = "about"
    url = "/about/"

  [[languages.en.menu.links]]
    name = "Privacy"
    weight = 1
    identifier = "privacy"
    url = "/privacy/"

  [[languages.en.menu.links]]
    name = "Imprint"
    weight = 2
    identifier = "impressum"
    url = "/impressum/"


[languages.de]
  languageCode = "de"
  languageName = "Deutsch"
  copyright = ""
  weight = 2

  [[languages.de.menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/de/"

  [[languages.de.menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/blog/"

  [[languages.de.menu.main]]
    name = "Über uns"
    weight = 3
    identifier = "about"
#    hasChildren = true
    url = "/about/"

#    [[languages.de.menu.main]]
#      parent = "about"
#      name = "Über Wiebke"
#      weight = 1
#      identifier = "wiebke"
#      url = "/about/wiebke/"

  [[languages.de.menu.links]]
    name = "Datenschutz"
    weight = 1
    identifier = "privacy"
    url = "/privacy/"

  [[languages.de.menu.links]]
    name = "Impressum"
    weight = 2
    identifier = "impressum"
    url = "/impressum/"

[languages.nl]
  languageCode = "nl"
  languageName = "Nederlands"
  copyright = ""
  weight = 3 

  [[languages.nl.menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/nl/"

  [[languages.nl.menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/blog/"

  [[languages.nl.menu.main]]
    name = "Over ons"
    weight = 3
    identifier = "about"
    url = "/about/"

  [[languages.nl.menu.links]]
    name = "Privacyverklaring"
    weight = 1
    identifier = "privacy"
    url = "/privacy/"

  [[languages.nl.menu.links]]
    name = "Informatie"
    weight = 2
    identifier = "impressum"
    url = "/impressum/"
